cookie:
  expiry_days: 30
  key: COURSEBOT_SECRET_2026
  name: coursebot_auth
credentials:
  usernames:
    lau:
      email: philip.lau@btech.au.dk
      name: lau
      password: $2b$12$u1SKKEQCMDpaRX2K9X4l5.S6J.m2KuRHFJODkMKo3kFN8fMzJvHti
      role: teacher
